<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHbU1FCJ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHbU1FCJ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHbU1FCJ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHbU1FCJ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHbU1FCJ\appAppKernelProdContainer([
    'container.build_hash' => 'HbU1FCJ',
    'container.build_id' => 'a778f38d',
    'container.build_time' => 1698217562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHbU1FCJ');
