<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpsa69u\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpsa69u/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZpsa69u.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZpsa69u\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZpsa69u\appAppKernelProdContainer([
    'container.build_hash' => 'Zpsa69u',
    'container.build_id' => 'ef7ca107',
    'container.build_time' => 1725272800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpsa69u');
